### ISSUE TITLE
Incorrect view during scroll

### ISSUE THREAD

**Issue by ZedZipDev** [excubo-ag/Blazor.Grids#1]
I have an Index.razor
```
@page "/"
@using Excubo.Blazor.Grids
<h1>Dashboard</h1>
<Dashboard AspectRatio="1.5">
    <Columns Count="2" />
    <Rows Count="3" />
    <Element Row="0" Column="0"><HorizontalBarChartComponent /></Element>
    <Element Row="0" Column="1"><SimpleBarChartComponent /></Element>
    <Element Row="1" Column="0"><PMPieChartComponent /></Element>
    <Element Row="1" Column="1"><DoughnutChartComponent /></Element>
    <Element Row="2" Column="0"><StackedBarChartComponent /></Element>
    <Element Row="2" Column="1"><TimeBarChartComponent /></Element>
</Dashboard>

@code { }
```

And sometimes when I scroll the page it looks incorrect : the "Dashboard"  header hides, its ok, but cell titles do not hide.
See attachments
How I can fix it? 

<img width="340" alt="Capture01" src="https://user-images.githubusercontent.com/25686753/88476020-2c335780-cf35-11ea-9bb1-57d1f075929b.PNG">
<img width="420" alt="Capture02" src="https://user-images.githubusercontent.com/25686753/88476022-2ccbee00-cf35-11ea-9ef5-732a51fb5656.PNG">

**Comment by stefanloerwald** [comment]
Hi @Oleg26Dev,

It seems to me that this is actually an issue in the blazor template. https://github.com/dotnet/aspnetcore/issues/22895 looks like the related issue. It was recently fixed, it seems, so I would expect the fix to be included in the new templates for .Net 5 latest. 

Could you please see whether the discussed fix on the issue over in the aspnetcore repo solves your issue too? 

Thanks
Stefan

**Comment by ZedZipDev** [comment]
Thank you @stefanloerwald ,  you are right, i have changed the site.css, it was fixed
