### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by abulka** [excubo-ag/Blazor.Grids#17]
The demo link https://excubo-ag.github.io/Blazor.Grids/ is not working - displays `An unhandled error has occurred.` during load, and the console is full of errors.

**Comment by stefanloerwald** [comment]
Thank you @abulka for raising this. This actually is just an error in the workflow which happened to another demo page too. So after re-running that same workflow, the site is working again. Please let me know if that isn't the case for you.

Thanks
Stefan
