### ISSUE TITLE
Not able to move untitled elements in dashboard?

### ISSUE THREAD

**Issue by white-jacob-dev** [excubo-ag/Blazor.Grids#20]
It looks like the moveable feature of elements are tied to the title of each element so that if you remove them, the elements are no longer moveable? Not sure if I'm missing something here...

**Comment by stefanloerwald** [comment]
That's correct. One can only grab onto the header to move elements. That's by design, as elements may have interactive components themselves.

**Comment by white-jacob-dev** [comment]
Is there a way to target the title div? Just so I can add custom styling

**Comment by stefanloerwald** [comment]
There's no id or class on the div, so that's not something you can use. I suppose it might be possible to target the first div child of the div with class `eg-elc` (the class on each element).
