### ISSUE TITLE
Drag and drop between grids

### ISSUE THREAD

**Issue by jaspervanmegroot** [excubo-ag/Blazor.Grids#26]
Hello,

I am working on your project, and I would like to know if it's possible to drag components between two grids using Blazor.Grids.

Thank you, and best regards!

Jasper

**Comment by stefanloerwald** [comment]
Hi Jasper,

This is not supported and there's no plan for this. I'm curious: what would be the benefit of using multiple grids?

Stefan

**Comment by jaspervanmegroot** [comment]
Hi Stefan,

I want to drag from a different grid or list like the advanced demo in Blazor:
https://gridstackjs.com/#demo 

Is this possible with your project?

Jasper

**Comment by stefanloerwald** [comment]
As I said before, it's not possible to move elements between two grids in this project. It doesn't feel like something that's easy to achieve with the design of grids in this project, but of course you're free to take it as a starting point in your project.

**Comment by jaspervanmegroot** [comment]
Oke thanks ;)
