### ISSUE TITLE
DragAndDrop between Containers

### ISSUE THREAD

**Issue by SmartSquareAZ** [excubo-ag/Blazor.Grids#29]
Hello,

not an issue but a question regarding your library.

Is it possible to drag and drop elements from one container to another container? Like from a sidebar into a main grid, where the sidebar holds all available elements and the main grid is for building a dashboard? If yes, is there any documentation regarding this?

Best regards 😊

**Comment by stefanloerwald** [comment]
Hi @SmartSquareAZ 

This is is not supported and likely not easy to implement into the existing code.

Best
Stefan
